GccBlogSite/GccBlogSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GccBlogSite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail')

]

GccBlogSite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField, CKEditorWidget
from ckeditor import widgets
# Create your models here.

STATUS =(
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    thumbnail = models.ImageField(upload_to='images', null=True)
    objects = models.Manager()
    #print("ok")

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

GccBlogSite/blog/views.py
from django.views import generic
from .models import Post

# Create your views here.


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = 'index.html'
    paginate_by = 3



class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

GccBlogSite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Greek Code Community</title>
            <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #1c1b1b;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Greek Code Community</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-light">
                            <a class="nav-link text-light font-weight-bold" href="#">About</a>
                        </li>
                        <li class="nav-item text-light">
                            <a class="nav-link text-light font-weight-bold" href="#">Policy</a>
                        </li>
                        <li class="nav-item text-light">
                            <a class="nav-link text-light font-weight-bold" href="#">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-dark">
            <p class="m-0 text-light text-center">Copyright &copy; <a href="https://www.facebook.com/GreekCodecommunity"
                                                                      target="_blank"
                                                                      class="text-light">Greek Code Community</a>
            </p>
        </footer>
    </body>
</html>

GccBlogSite/templates/index.html
{% extends "base.html" %}

 {% block content %}
<style>

    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    .head_text{
    color: white;
  }
    .card{
    box-shadow: 0 16px 48px #E3E7EB;
}
</style>

    <header class="masthead" >
            <div class="overlay"></div>
            <div class="container">
              <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                  <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to our Blog</h3>
<!--                    <p class="text-light"> Greek Code Community..! &nbsp-->
<!--                    </p>-->
                </div>
                    </div>
                  </div>
                </div>
            </div>
    </header>


            <div class="container">
                <div class="row">
              <!-- Blog Entries Column -->
                    <div class="col-md-8 mt-3 left">
                        {% for post in post_list %}
                <div class="card mb-4" >
                    <img src=" {{ post.thumbnail.url }} " class="img-responsive card-img-top">
                  <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.Author }} | {{ post.created_on}} </p>
                    <div class="card-text">{{post.content|safe|slice:":100" }}</div>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                  </div>
                </div>
                {% endfor %}
            </div>
                {% block sidebar %}
                {% include 'sidebar.html' %}
                {% endblock sidebar %}
            </div>
        </div>

        {% if is_paginated %}
          <nav aria-label="Page navigation conatiner"></nav>
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
          </ul>
          </nav>
        </div>
        {% endif %}

{%endblock%}

GccBlogSite/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4 mt-3 left top mt-3">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class="text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <div class="card-text "> {{ object.content | safe }} </div>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

GccBlogSite/templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text">Some text....bla bla <br>blaahaaha</p>
        <a href="#"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>

{% endblock sidebar %}